# AI 4week 실습 과제
#### pytorch matrix multiplication

- matrix multiplication
- batch matrix multiplication
- matmul
- @ operator

In [1]:
!pip3 install torch==1.9.0 torchvision torchaudio

     |████████████████████████████████| 1.9 MB 5.1 MB/s 
     |████████████████████████████████| 1.9 MB 32.0 MB/s 


In [2]:
import torch

## 0. [Broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html#broadcasting-semantics)

In [3]:
# broadcasting
a = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])

print((a+10).size())
print(torch.add(a, 10).size())
print(a+10)

torch.Size([2, 3])
torch.Size([2, 3])
tensor([[11., 12., 13.],
        [14., 15., 16.]])


In [4]:
x = torch.FloatTensor(5,1,4,1)
y = torch.FloatTensor(  3,1,1)
print((x+y).size())
print((x-y).size())
print((x.matmul(y)).size())

torch.Size([5, 3, 4, 1])
torch.Size([5, 3, 4, 1])
torch.Size([5, 3, 4, 1])


In [5]:
# -- broadcasting  1 -- #
# [5, 3, 2, 3] x [3, 4] = [5, 3, 2, 4]
a = torch.randn(5, 3, 2, 3)
b = torch.randn(3, 4)

res1 = torch.matmul(a, b)
res2 = a@b

print(res1.size(), res2.size())

# -- broadcasting  2 -- #
a = torch.randn(10, 3, 4)
b = torch.randn(4)
print(torch.matmul(a, b).size())
print((a@b).size())

torch.Size([5, 3, 2, 4]) torch.Size([5, 3, 2, 4])
torch.Size([10, 3])
torch.Size([10, 3])


In [6]:
x = torch.ones(1,3,1)
y = torch.ones(3,1,7)

res = x.add_(y)
print(res.size())
print(res)

RuntimeError: ignored

## 1. [torch.mm](https://pytorch.org/docs/stable/generated/torch.mm.html)

In [7]:
a = torch.randn(2, 3)
b = torch.randn(3, 4)
print(torch.mm(a, b).size()) #[2, 3] x [3, 4]= [2, 4]
print(torch.mm(a,b))

torch.Size([2, 4])
tensor([[-0.6884,  1.1831,  0.5899, -2.2066],
        [ 0.0039,  0.3859,  1.1798, -2.2313]])


## 2. [torch.bmm](https://pytorch.org/docs/stable/generated/torch.bmm.html)

In [8]:
a = torch.randn(10, 2, 3)
print(a[1])
b = torch.randn(10, 3, 4)
print(b[1])
print(torch.bmm(a, b).size())
print(torch.bmm(a, b))

tensor([[ 0.4446,  2.4250,  0.4816],
        [-1.1471, -0.5561,  1.3311]])
tensor([[-0.3633,  1.8805, -1.4860, -1.6845],
        [ 0.1643,  0.1679,  0.8737, -0.0781],
        [-0.5128, -0.4658,  1.2077,  0.5905]])
torch.Size([10, 2, 4])
tensor([[[-2.7399, -0.5463,  0.8225,  1.7603],
         [ 0.3067,  0.6802, -0.8302,  0.3505]],

        [[-0.0100,  1.0188,  2.0397, -0.6541],
         [-0.3571, -2.8706,  2.8263,  2.7617]],

        [[ 0.1871, -0.4606,  0.5230,  0.2022],
         [-0.9508,  1.7865, -4.5657, -0.2833]],

        [[ 0.8718,  0.2276, -1.2175, -0.1586],
         [ 1.0783,  1.5058, -0.4938,  0.1298]],

        [[ 0.4812,  1.4944, -0.2412, -2.0278],
         [ 1.8604,  2.2196, -2.3966, -1.1427]],

        [[-1.4118,  0.8808,  0.9876,  1.1626],
         [ 3.0262,  0.4430,  1.5026,  1.5227]],

        [[-1.0533,  1.1621, -9.5032,  3.7385],
         [-1.2748, -0.4816,  0.6658, -1.4935]],

        [[ 2.3864, -0.3735,  0.1454, -0.6233],
         [ 3.1805, -0.2990,  0.3230, -0.6915

## 3. [torch.matmul](https://pytorch.org/docs/stable/generated/torch.matmul.html)

[1] vector x vector (두 tensor 모두 1-dim)

[2] matrix x matrix (두 tensor 모두 2-dim)

[3] 첫번째 tensor 1-dim, 두번째 tensor 2-dim

[4] 첫번째 tensor 2-dim, 두번째 tensor 1-dim

In [9]:
# -- 1 -- #
a = torch.randn(5)
print(a)
b = torch.randn(5)
print(b)
print(torch.matmul(a, b).size())
print(torch.matmul(a, b))

tensor([ 0.1115, -0.8215, -0.7674,  0.7654, -1.3451])
tensor([ 0.6591,  1.3273,  0.9079,  0.2446, -0.8851])
torch.Size([])
tensor(-0.3359)


In [10]:
# -- 2 -- #
a = torch.randn(3, 4)
print(a)
b = torch.randn(4, 5)
print(b)
print(torch.matmul(a, b).size())
print(torch.matmul(a, b))

tensor([[ 1.5073,  0.7732, -1.3870,  0.2983],
        [ 0.0255,  0.9407,  0.7949,  0.1127],
        [ 1.5484,  0.8303, -0.0338, -2.2111]])
tensor([[ 0.6110, -2.5979, -0.8997,  1.1737, -0.0162],
        [ 0.7907, -0.6883,  0.7996,  0.5632,  1.4080],
        [-0.6778,  0.8665, -0.6154,  1.0911, -0.9106],
        [-1.4821, -0.0833,  0.3001,  0.3882,  0.6611]])
torch.Size([3, 5])
tensor([[ 2.0303, -5.6748,  0.2051,  0.8070,  2.5245],
        [ 0.0536, -0.0344,  0.2739,  1.4708,  0.6748],
        [ 4.9026, -4.4394, -1.3721,  1.3897, -0.2869]])


In [11]:
# -- 3 -- #
a = torch.randn(3) # [3] -> [(1), 3]
print(a)
b = torch.randn(3, 4)
print(b)
print('\n\nresult : ', torch.matmul(a, b))
print(torch.matmul(a, b).size()) # [1, 3] x [3, 4] = [1, 4] => [4]



tensor([-1.9429, -1.1799,  0.8365])
tensor([[-0.0629, -0.9833, -2.3997, -0.6287],
        [-0.5534, -1.7407, -0.1623,  1.3599],
        [ 0.6748,  2.1346,  1.6902,  1.5193]])


result :  tensor([1.3397, 5.7497, 6.2675, 0.8878])
torch.Size([4])


In [12]:
# -- 4 -- #
a = torch.randn(3, 4)
print(a)
b = torch.randn(4)
print(b)
print('\n\nresult : ', torch.matmul(a, b))
print(torch.matmul(a, b).size()) # [3, 4] x [4] = [3, 1]

tensor([[-0.0586, -0.1232,  1.0634, -0.5204],
        [ 1.9617, -0.8000,  0.0999,  0.7756],
        [-0.9439, -1.2233,  1.3684,  0.0046]])
tensor([ 0.3190,  0.0286, -1.2052, -0.3299])


result :  tensor([-1.1322,  0.2268, -1.9869])
torch.Size([3])


[5] batched matrix multiply (두 tensor 모두 1-dim 이상, 하나의 tensor N-dim)

- batched matrix x broadcasted vector

- batched matrix x batched matrix 

- batched matrix x broadcasted matrix

In [13]:
batch_size = 10

# -- batched matrix x broadcasted vector -- #
a = torch.randn(batch_size, 3, 4)
print(a[0])
b = torch.randn(4)
print(b)
print(torch.matmul(a, b).size())
print(torch.matmul(a, b))



tensor([[ 0.6898,  0.8835, -0.5664, -0.5129],
        [ 1.6732, -2.3487,  0.4547,  0.7303],
        [-0.0751, -0.1284,  0.1434, -1.6282]])
tensor([ 1.1904,  0.0303, -0.2320,  0.7071])
torch.Size([10, 3])
tensor([[ 0.6166,  2.3315, -1.2778],
        [-0.8101, -0.0396, -0.9244],
        [ 0.0850,  0.9861, -1.3184],
        [ 0.0261, -0.7287,  1.3359],
        [ 1.5719, -0.3294, -0.0318],
        [-0.2048,  2.5461, -1.4905],
        [-0.6434,  2.1012, -0.1017],
        [-0.4508,  0.6856,  0.6877],
        [ 1.4790, -2.2307, -0.6888],
        [-2.4789,  0.5605,  3.2967]])


In [14]:
# -- batched matrix x batched matrix -- #
a = torch.randn(batch_size, 3, 4)
b = torch.randn(batch_size, 4, 5)
print(torch.matmul(a, b).size())

# -- batched matrix x broadcasted matrix -- #
a = torch.randn(batch_size, 3, 4) # [10, 3, 4]
b = torch.randn(4, 5) # [(1), 4, 5]
print(torch.matmul(a, b).size()) 

torch.Size([10, 3, 5])
torch.Size([10, 3, 5])




```
# 코드로 형식 지정됨
```

## 4. @ operator

In [15]:
# [2, 3] x [3, 2] = [2, 2]
a = torch.tensor([[1, 2, 3], [4, 5, 6]]) # [2, 3]
b = torch.tensor([[2, 2], [2, 2], [2, 2]]) # [3, 2]

res1 = torch.matmul(a, b)
res2 = a@b

print(res1.size(), res2.size())
print('res1 : ', res1)
print('res2 : ', res2)

# [2, 3] x [3, 2] x [2, 1] = [2, 1]
a = torch.tensor([[1, 2, 3], [4, 5, 6]]) # [2, 3]
b = torch.tensor([[2, 2], [2, 2], [2, 2]]) # [3, 2]
c = torch.tensor([[3], [3]]) # [2, 1]

res1 = torch.matmul(torch.matmul(a, b), c) # (a @ b) @ c
res2 = a@b@c

print(res1.size(), res2.size())
print('res1 : ', res1)
print('res2 : ', res2)

torch.Size([2, 2]) torch.Size([2, 2])
res1 :  tensor([[12, 12],
        [30, 30]])
res2 :  tensor([[12, 12],
        [30, 30]])
torch.Size([2, 1]) torch.Size([2, 1])
res1 :  tensor([[ 72],
        [180]])
res2 :  tensor([[ 72],
        [180]])


In [16]:
a = torch.randn(10, 1, 2, 3)
b = torch.randn(5, 3, 2) # -> [10,5,3,2]
print(torch.matmul(a, b).size())  # (2,3) * (3,2) => (2,2)

torch.Size([10, 5, 2, 2])


In [17]:
a = torch.randn(10, 2, 3, 4)
b = torch.randn(1, 4, 3)  # -> (10, 2, 4, 3)
print(torch.matmul(a, b).size())  #(3,4) * (4,3) ->(3,3)

torch.Size([10, 2, 3, 3])


In [18]:
a = torch.randn(10, 5, 2, 3)
b = torch.randn(5, 3, 2)
print(torch.matmul(a, b).size())

torch.Size([10, 5, 2, 2])


In [19]:
a = torch.randn(10, 2, 3, 4)
b = torch.randn(4)
print(torch.matmul(a, b).size())

torch.Size([10, 2, 3])


In [20]:
a = torch.randn(10, 2, 1, 4, 5) # -> [10,2,5,4,5]
b = torch.randn(5, 5, 4) # ->[10,2,5,5,4]
print(torch.matmul(a, b).size())

torch.Size([10, 2, 5, 4, 4])


- 실습 과제 

In [22]:
# 과제1) [a,1,b,b] x [c,b,b] = [a,c, b,b]

A = torch.randn(3,1,2,2)
B = torch.randn(5,2,2)
print(torch.matmul(A,B).size())

torch.Size([3, 5, 2, 2])


In [23]:
# 과제2) [a,1,b,c] x [d,c,b] = [a,d, b,b]

A = torch.randn(3,1,2,3)
B = torch.randn(5,3,2)
print(torch.matmul(A,B).size())

torch.Size([3, 5, 2, 2])


In [24]:
# 과제3) [a,e,b,c] x [d,c,b] = ERROR  # e != 1인경우

A = torch.randn(3,2,2,3)
B = torch.randn(5,3,2)
print(torch.matmul(A,B).size())

RuntimeError: ignored

과제 3의 경우 브로드 캐스팅 조건을 만족하지 못했다.  
B의경우 A와 같은 차원을 만들어주기 위해 앞의 차원이 하나 더 늘어나게된다.  
이후 A, B 두번째 인덱스 값은 각각 2와 3으로 둘중하나가 1이 되어야 한다는 조건을 만족하지 못하게 된다.  
그래서 에러가 뜨게된다.


In [25]:
# 과제4) [a,b,1,c,d] x [e,d,f] = [a,b,e, c,f]

A = torch.randn(3,2,1,4,5)
B = torch.randn(6,5,8)
print(torch.matmul(A,B).size())

torch.Size([3, 2, 6, 4, 8])


In [26]:
# 과제5) [a,1,b,c,d] x [e,b,d,f] = [a,e,b,c,f]

A = torch.randn(3,1,2,4,5)
B = torch.randn(6,2,5,8)
print(torch.matmul(A,B).size())

torch.Size([3, 6, 2, 4, 8])


In [27]:
# 과제6) [a,b,c,d,e,f] x [b,c,f,g] = ERROR

A = torch.randn(3,4,5,6,7,8)
B = torch.randn(4,5,8,9)
print(torch.matmul(A,B).size())

RuntimeError: ignored

과제6의 경우 브로드 캐스팅 조건을 만족하지 못했다.  
둘중하나가 1이 되어야 한다는 조건을 위배로 에러 발생

In [36]:
# 과제7) [a,b,c,d,e,f] x [1,c,d,f,a] = [a,b,c,d,e,a]

A = torch.randn(3,4,5,6,2,7)
B = torch.randn(1,5,6,7,3)
print(torch.matmul(A,B).size())

torch.Size([3, 4, 5, 6, 2, 3])


In [40]:
# 과제8) [g,a,b,c,d,e,f] x [1,c,d,f,a] = [g,a,b,c,d,e,a]

A = torch.randn(9,3,4,5,6,2,7)
B = torch.randn(1,5,6,7,3)
print(torch.matmul(A,B).size())

torch.Size([9, 3, 4, 5, 6, 2, 3])


In [42]:
# 과제9) [h,g,a,b,c,d,e,f] x [a,1,c,d,f,a] = [h,g,a,b,c,d,e,a]

A = torch.randn(8,9,3,4,5,6,2,7)
B = torch.randn(3,1,5,6,7,3)
print(torch.matmul(A,B).size())

torch.Size([8, 9, 3, 4, 5, 6, 2, 3])


In [57]:
# 과제10) [h,g,a,b,c,d,e,f] x [a,c,c,d,f,a] = ERROR

A = torch.randn(8,9,3,4,5,6,2,7)
B = torch.randn(3,5,5,6,7,3)
print(torch.matmul(A,B).size())

RuntimeError: ignored

두 텐서 간브로드캐스팅 조건
- 각 tensor는 최소 1-dim 이상
- dim zie가 같음
- 둘 중 하나가 1
- 둘 중 하나가 없음

연산 결과로 나오는 tesnor zie는 두 텐서 사이즈의 최대값

과제 예제 10의 경우 위의 10예제에서 B의 두번째 인덱스 값을 1에서 5로 바꾸었다. 둘 중 하나가 1인 것을 위배해서 ERROR가 발상한다.

In [58]:
print('감사합니다!!')

감사합니다!!
