In [1]:
import numpy as np

In [2]:
ralo = 2400
print(ralo)
print(type(ralo))

bool1 = True
print(bool1)
print(type(bool1))


2400
<class 'int'>
True
<class 'bool'>


In [3]:
c = 'ABC'
print(c)
print(type(c))
d = [1, '2', 3]
print(d)
print(type(d))
e = {'a': 10, 'b': 20}
print(e)
print(type(e))
f = {10, 20, 30}
print(f)
print(type(f))

ABC
<class 'str'>
[1, '2', 3]
<class 'list'>
{'a': 10, 'b': 20}
<class 'dict'>
{10, 20, 30}
<class 'set'>


In [5]:
ac = np.array([1, 2, 3])
print(ac)
print(ac.shape)
print(ac.ndim)
print(ac.dtype)
print(ac.itemsize)
print(ac.size)


[1 2 3]
(3,)
1
int64
8
3


In [13]:
ab = np.array([[1, 2, 3], [5,6,7]])
print(ab)
print(ab.shape)
print(ab.ndim)
print(ab.dtype)
print(ab.itemsize)
print(ab.size)

[[1 2 3]
 [5 6 7]]
(2, 3)
2
int64
8
6


In [15]:
A = np.array([10, 11, 12 , 13, 14])
B = np.array([0, 1, 2, 3, 4])
print(A +B)
print(A-B)

[10 12 14 16 18]
[10 10 10 10 10]


In [16]:
C = np.array([[5,6],[7,8]])
D = np.array([[10,20],[30,40]])
print(C+D)
print(C-D)

[[15 26]
 [37 48]]
[[ -5 -14]
 [-23 -32]]


In [17]:
E = np.array([[100,100],[200,0]])
F= np.array([[10,20],[30,40]])

print(E+F)
print(E-F)

[[110 120]
 [230  40]]
[[ 90  80]
 [170 -40]]


In [21]:
A=np.array([[19,22],[13,22]])
B = np.array([[1,1],[2,2]])
C = np.dot(A,B)

print(C)

[[63 63]
 [57 57]]


In [24]:
A = np.array([[1,2],[3,4]])
print(A.transpose())
print(np.transpose(A))

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [25]:
A = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(A.transpose())
print(np.transpose(A))

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [26]:
A = np.array([[0,1],[2,3]])
print(np.linalg.inv(A))

[[-1.5  0.5]
 [ 1.   0. ]]


In [29]:
B = np.array([[6,2,],[9,0]])
print(np.linalg.inv(B))

[[ 0.          0.11111111]
 [ 0.5        -0.33333333]]
